### ISSUE TITLE
qt 5.12.4 ubuntu build gets fatal error: QtCore/QtGlobal: No such file or directory

### ISSUE THREAD

**Issue by pwcushman** [ftylitak/qzxing#118]
I am trying to build with Qt 5.12.4 on an Ubuntu 16.04 system.

Here is the compiler output:
g++ -pipe -Wunused-parameter -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DWICKR_SDK_SHARED -DWICKRPROTO_SHARED -DQZXING_QML -DQZXING_MULTIMEDIA -DWICKR_LOGGING_ENABLED=1 -DWICKR_NPL_ENABLED=1 -DWICKR_CHANGE_PW_ENABLED=1 -DWICKR_DEBUG -DWICKR_ALPHA -DQT_LIBEXEC_PATH=\"/usr/local/wickr/Qt-5.12/libexec\" -DHUNSPELL_STATIC=1 -DQT_QUICKWIDGETS_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_LOCATION_LIB -DQT_POSITIONINGQUICK_LIB -DQT_QUICK_LIB -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBVIEW_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORKAUTH_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB    ../../../wickr-desktop/libs/qzxing/src/QZXing.cpp   -o ../../../wickr-desktop/libs/qzxing/src/QZXing
In file included from ../../../wickr-desktop/libs/qzxing/src/QZXing.h:20:0,
                 from ../../../wickr-desktop/libs/qzxing/src/QZXing.cpp:1:
../../../wickr-desktop/libs/qzxing/src/QZXing_global.h:20:27: fatal error: QtCore/QtGlobal: No such file or directory

Building with the master branch pulled Monday of this week.

**Comment by ftylitak** [comment]
Hello @pwcushman 

i have experienced this issue quite a lot of times in the past and i never understood which was its solution to be honest. I believe it has something to do with your build environment but unfortunatelly I am not sure what to suggest to you. 

The only thing I know is that the build passes for Linux based on the CI: https://travis-ci.com/ftylitak/qzxing/jobs/213916020

Do you by any chance assign a value to the CONFIG tag of the "pro" file instead of adding/appending?
Example: 
```pro
CONFIG = qzxing_multimedia
```
instead of 
```pro
CONFIG += qzxing_multimedia
```

**Comment by pwcushman** [comment]
Thanks for the quick response.

in qtcreator, in the Build Steps we add the "CONFIG+=qzxing_multimedia" to the additional arguments.

**Comment by pwcushman** [comment]
FYI, In our environment we include the QZXing.pro via subdir:
TEMPLATE = subdirs

SUBDIRS = \
    qzxing/src/QZXing.pro

CONFIG += ordered

Not by including the QZXing.pri file in our .pro file.

**Comment by pwcushman** [comment]
Apparently the -I statements are not part of the compile statement.  I don't know why they are getting stripped out when the QZXing files are being built.

**Comment by pwcushman** [comment]
Okay so I think I figured out the issue.  Probably a Qt issue, but you can eliminate the problem as well.
In a separate directory we have the following include statement:
#include <QZXing>
This is causing the confusion cause the QZXing is becoming a dependency in the makefile for that other directory.  It then tries to build QZXing.cpp in that directory, which it shouldn't do, and it will fail cause there are no -I statements as well.

I did a workaround for now by putting the contents of the QZXing file into our file and things compile and build fine now.

I think having the QZXing file in the same directory and name as the QZXing.cpp file is causing the confusion for qmake.  Maybe just changing the name to something else would work.

**Comment by ftylitak** [comment]
Interesting that it got solved by this change. I will try to reproduce the behavior. 

Did you by any change forgot to add the -lQZXing at your main project. This makes me wonder at which folder will the QZXing.so file will be generated to be usable by the compiler for your project and your configuration. I need to look it up.

**Comment by pwcushman** [comment]
I tried the change based on the referenced issue you mentioned, but it did not help.  There is still an include statement in qzxing/src/QZXingImageProvider.cpp using <QZXing> instead of "QZXing.h" which may still be causing issue.

BTW, I am not getting this issue on all my environments (Mac, Windows and Ubuntu).  I'm at a loss as to what to do.

I could be environment related, but it seems that once the problem occurs on the environment it is impossible to get rid of.

**Comment by pwcushman** [comment]
I am building as a subdir currently.  Have not tried by including the QZXing.pri

**Comment by pwcushman** [comment]
I really think something in Qt is getting confused since the Target = QZXing and there is a file QZXing in your source directory.  I think just renaming that file to something else will work.  It actually did work for me by doing that.

**Comment by pwcushman** [comment]
I am not building off of master either.  I see you have changed qzxing/src/QZXingImageProvider.cpp to include "QZXing.h"

**Comment by pwcushman** [comment]
Okay, so I moved our application to use the latest master code and with the "QZXing.h" include it is building fine.

**Comment by ftylitak** [comment]
Closing the issue as it should already be resolved by https://github.com/ftylitak/qzxing/commit/10ba99586e955ae1be12114fb7a7bb60e0ba809e. 

In case of futher errors, please open a new issue.
