### ISSUE TITLE
Compilation error in QZXing::registerQMLTypes

### ISSUE THREAD

**Issue by oKcerG** [ftylitak/qzxing#16]
> ../../src/QZXing.h:84:19: error: 'QZXingFilter' was not declared in this scope
   `qmlRegisterType<QZXingFilter>("QZXing", 2, 3, "QZXingFilter");`

It seems this is caused by https://github.com/ftylitak/qzxing/commit/75eb47e8c5e504891b36230b8f6b331217e33481

**Comment by oKcerG** [comment]
Thanks for the fast reaction :)
Bur there is still a compilation error (now in QZxIngFilter.h) :
>In file included from ../../src/QZXing.h:19:0,
                 from ../QZXingLive/main.cpp:8:
../../src/QZXingFilter.h:76:9:` error: 'QZXing' does not name a type

I guess this comes from the cyclic inclusion of QZXing and QZXingFilter.
The registerType (and imageProvider maybe) definition should be in QZXing.cpp

**Comment by ftylitak** [comment]
Reopening till I get  confirmation from @oKcerG

**Comment by ftylitak** [comment]
I am closing this issue since the compilation issue was fixed and I would like to decouple this issue from the #17.
